### ISSUE TITLE
Facing issue in safari browsers for account section

### ISSUE THREAD

**Issue by irajneeshgupta** [graphcommerce-org/graphcommerce#1421]
### Provide environment information

i have added my env for public graphql. 

### What browser are you using? (if relevant)

safari : 15.4.1

### How are you deploying your application? (if relevant)

vercel

### Describe the Bug

https://graphcommerce-rajneesh-49xony8fx-irajneeshgupta.vercel.app/
i have deployed this app on vercel and everything is perfect except the client side exception that i face in safari browser : 15.4.1 latest. 
Steps :
1. register a account
2. try to login same account
3. you will successfully logged in.
4. click on view account. (At this step it will try to fetch accont and not working for safari) for reference i added the screenshot
https://graphcommerce-rajneesh-49xony8fx-irajneeshgupta.vercel.app/account
![image](https://user-images.githubusercontent.com/18143480/165108223-d157c210-bd98-4baa-98cd-ff5380821e3b.png)

### Expected Behavior

It should open account details for logged in customer.

### To Reproduce

Steps :
My deployed instance: https://graphcommerce-rajneesh-49xony8fx-irajneeshgupta.vercel.app/

1. register a account
2. try to login same account
3. you will successfully logged in.
4. click on view account. (At this step it will try to fetch accont and not working for safari)

**Comment by irajneeshgupta** [comment]
@paales can you give some light on this.
i can't figure out what is the issue since i am using mobile device and can't enable web debugging on the device.

**Comment by paales** [comment]
@machielkreiken Can you perhaps give this a try and see if we can reproduce it?

**Comment by machielkreiken** [comment]
Hi @irajneeshgupta @paales 

I don't seem to have any issues. I've tried both desktop Chromium/Safari and mobile Safari. On all devices after logging in I can select the account icon in the header, and it will open the account for me.

This was all done on the provided instance link in the description.

Any other steps I could try to reproduce this @irajneeshgupta ?

![image](https://user-images.githubusercontent.com/28918979/165125235-fae5d80b-40f4-41e5-baf1-01aa2bcc8847.png)

**Comment by irajneeshgupta** [comment]
@machielkreiken 
i ran some tests and found that it is happening for certain customer accounts.
for fresh it is working so i consider it may be incosistent data issue from my instance
