### ISSUE TITLE
Mega Menu

### ISSUE THREAD

**Issue by shiwani27** [graphcommerce-org/graphcommerce#1423]
### Describe the feature you'd like to request

We need to show child items in the menu without having to recreate the entire menu

### Describe the solution you'd like

Please add the sub categories menu with parent category menus

### Describe alternatives you've considered

We have not considered alternatives yet

**Comment by paales** [comment]
@shiwani27 Have you got an example how you'd like the end result to look like?

As a developer, how would you like to see the current code to extendable?

**Comment by shiwani27** [comment]
Yes, we would like to see like this

![image](https://user-images.githubusercontent.com/52956276/165287602-239e797a-5e2b-434a-9df7-b1c7a100ec13.png)

**Comment by ErwinOtten** [comment]
I'm currently doing some experiments here: https://github.com/graphcommerce-org/graphcommerce/pull/1460

Preview: https://graphcommerce-git-feature-mega-menu-graphcommerce.vercel.app/
