### ISSUE TITLE
Error: useLingui hook was used without I18nProvider.

### ISSUE THREAD

**Issue by konyilwin** [graphcommerce-org/graphcommerce#1531]
### Provide environment information

Node v14.19.3

### What browser are you using? (if relevant)

Google Chrome

### How are you deploying your application? (if relevant)

yarn dev

### Describe the Bug

Server Error

Error: useLingui hook was used without I18nProvider.

This error happened while generating the page. Any console logs will be displayed in the terminal window.

Call Stack
useLingui
file:///Users/john/Documents/GitHub/ecom/node_modules/@lingui/react/cjs/react.development.js (21:13)
Trans
file:///Users/john/Documents/GitHub/ecom/node_modules/@lingui/react/cjs/react.development.js (246:20)
renderWithHooks
file:///Users/john/Documents/GitHub/ecom/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5658:16)
renderIndeterminateComponent
file:///Users/john/Documents/GitHub/ecom/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5731:15)
renderElement
file:///Users/john/Documents/GitHub/ecom/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5946:7)
renderNodeDestructiveImpl
file:///Users/john/Documents/GitHub/ecom/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///Users/john/Documents/GitHub/ecom/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:///Users/john/Documents/GitHub/ecom/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderChildrenArray
file:///Users/john/Documents/GitHub/ecom/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6211:7)
renderNodeDestructiveImpl
file:///Users/john/Documents/GitHub/ecom/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6141:7)

### Expected Behavior

It should work as graphcommerce demo store.

### To Reproduce

Install and use node 14: nvm install 14 && nvm use 14
Install yarn: npm install --global yarn

Download the example

git clone git@github.com:graphcommerce-org/graphcommerce.git
mkdir my-project
cp -R graphcommerce/examples/magento-graphcms/. my-project && rm -rf graphcommerce
cd my-project
cp -R .env.example .env
rm CHANGELOG.md
rm -rf node_modules && rm -rf .next

Edit /package.json. Delete "scripts": {...} and rename scripts_local to scripts:

yarn Instal
yarn codegen
yarn dev

**Comment by paales** [comment]
We've got the issue reproduced, fixing it now :)

**Comment by paales** [comment]
@konyilwin Fixed in latest release!
