### ISSUE TITLE
[RFC] Automatic upgrading of the package.json

### ISSUE THREAD

**Issue by paales** [graphcommerce-org/graphcommerce#1567]
### Describe the feature you'd like to request

At the moment is kinda error-prone to do an upgrade and I would say that about 50% of the issues reported when upgrading are due to a version mismatch, missing packages.

### Describe the solution you'd like

The tool should do the following:

- Update all known versions that are used, that means that all @graphcommerce/* packages can be upgraded as well as all the package versions of the example.
- Report missing packages that are in the example, but not in the local package.
- Report additional packages that are installed.

### Describe alternatives you've considered

Manual upgrades like we use now.

**Comment by Jessevdpoel** [comment]
I have created an issue on the backlog
