### ISSUE TITLE
"View shopping cart" button moves after "Complete your purchase" section loads (behaviour after adding product to cart on mobile)

### ISSUE THREAD

**Issue by KMalkowski** [graphcommerce-org/graphcommerce#1781]
### Describe the Bug

I think that a button after being displayed should stay in one place instead of being pushed to the top right after by the element below it. It's very easy to click on a product instead of a button and it's a frustrating experience for the user. 

### Expected Behavior

The "complete your purchase" products could load above the "view shopping cart" button (it wouldn't move in this case). I guess the same issue exists for the close cross icon on the top right corner of this whole element but I don't think that is that important as most people will probably close the element by tapping above it or sliding it down. 

### To Reproduce

Just add a product to the cart on a mobile device.

**Comment by paales** [comment]
Fix incoming https://github.com/graphcommerce-org/graphcommerce/pull/1870

**Comment by paales** [comment]
Fix released on canary, will be available in the next release: https://graphcommerce-git-canary-graphcommerce.vercel.app/nl/p/bedazzled-gc-112-sock
