### ISSUE TITLE
Wrong parsing of limit parameter

### ISSUE THREAD

**Issue by vahe-templi** [graphcommerce-org/graphcommerce#1906]
### Describe the Bug

bug parseParams function in 
@graphcommerce/magento-product/components/ProductListItems/filteredProductList.
It should use the value of the "limit" parameter. 

### Expected Behavior

It should use the value of the "limit" parameter. 

### To Reproduce

It uses the "limit" string.

**Comment by paales** [comment]
Fixed in https://github.com/graphcommerce-org/graphcommerce/pull/1914, will be available with the next GraphCommerce release

**Comment by paales** [comment]
@vahe-templi We'll be implementing some additional funtionality to make it work out of the box

**Comment by paales** [comment]
Any objection to renaming it to `page-size` in the URL, seems more logical than `limit` which is more of an SQL concept.

**Comment by paales** [comment]
I've added screenshots to the PR https://github.com/graphcommerce-org/graphcommerce/pull/1914
Please test out the functionality on the demo branch: https://graphcommerce-git-fix-various-graphcommerce.vercel.app/

Without any further feedback I'll proceed with merging the PR

**Comment by vahe-templi** [comment]
Thank you @paales !
