### ISSUE TITLE
Duplicate "graphql" modules cannot be used at the same time

### ISSUE THREAD

**Issue by vahe-templi** [graphcommerce-org/graphcommerce#2008]
### Describe the Bug

Tried to install the latest 6.2.0-canary.67 version, but got error when trying to run "yarn codegen" or "yarn build"
<img width="767" alt="Screen Shot 2023-07-28 at 17 14 45" src="https://github.com/graphcommerce-org/graphcommerce/assets/127774617/7ce3e305-2922-44f7-9747-e8e7ef906dbf">

### Expected Behavior

Build and codegen should run successfully.

### To Reproduce

Try to install the latest 6.2.0-canary.67 version and run "yarn codegen" or "yarn build"

**Comment by Giovanni-Schroevers** [comment]
Hey @vahe-templi thanks for reporting this issue!

We will be looking into a fix but in the mean time you can do the following as a temporary workaround:

- Go into your `yarn.lock` file
- Find `@hygraph/management-sdk` and `graphql-codegen-typescript-validation-schema` and change the version of the `graphql` dependency to `16.6.0`
- Remove node_modules and run `yarn` again

Both `yarn codegen` and `yarn dev` should now work again. If not try running `yarn list graphql` and change the dependency to `graphql` in any packages that show up there in the `yarn.lock` as well

**Comment by Giovanni-Schroevers** [comment]
@vahe-templi This has been fixed in 6.2.0-canary.69
