### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by nikilmethew** [graphcommerce-org/graphcommerce#2019]
### Describe the Bug

Creating the Hygraph account and adding the required configuration.

https://us-east-1-shared-usea1-02.cdn.hygraph.com/content/cll6kvnx81c9901t7aaxdhn5v/master
Magento_url/graphql

After adding the configuration details in the graphcommerce.config.js the site is not working.

![image](https://github.com/graphcommerce-org/graphcommerce/assets/46815046/24bb7053-3472-4568-9426-fbec95f5eb02)

### Expected Behavior

We follow the instructions, but after adding all configurations, the site throws error. 

### To Reproduce

Use the default configurations (graphcommerce.config.js) the site is working fine.
We add our Magento and hygraph url then the site is not working

**Comment by paales** [comment]
- Make sure you have ran `yarn codegen` after changing the URL's and it runs successfully.
- Clear site data -> Followed by an immediate refresh, It can be that there still is some remnants left in your cart.

<img width="781" alt="Scherm­afbeelding 2023-08-11 om 15 37 05" src="https://github.com/graphcommerce-org/graphcommerce/assets/1244416/5c07f63e-e735-44bd-a9dc-02e2b68f0e43">

**Comment by nikilmethew** [comment]
@paales,
Thanks for your support, After run the commands the site is working fine.
