### ISSUE TITLE
[codegen] graphql-codegen -w exited with code SIGTERM

### ISSUE THREAD

**Issue by eugeneyvt** [graphcommerce-org/graphcommerce#2056]
### Describe the Bug

I’m trying to run yarn dev, the app seems to be compiled and says “waiting for changes in…”, but when I try to connect to it with a browser (nginx to proxy), I receive the following error:

`[codegen] graphql-codegen -w exited with code SIGTERM`

And it exits with code 1

_Also, there's still an issue with types when running 'build' but I found a solution in the threads, though haven't tried yet_

Thank you!

### Expected Behavior

Web app available via the browser and domain

### To Reproduce

nvm install 16
corepack enable
git clone -b main --depth 1 https://github.com/graphcommerce-org/graphcommerce.git
mkdir my-project
cp -R graphcommerce/examples/magento-graphcms/. my-project && rm -rf graphcommerce && cd my-project
yarn
yarn codegen
yarn dev

**Comment by paales** [comment]
The provided installation steps work as expected
