### ISSUE TITLE
Type Error during Compilation

### ISSUE THREAD

**Issue by tw-ayas** [graphcommerce-org/graphcommerce#2057]
### Describe the Bug

Compilation Fails due to type error on Ubuntu Server. 
"Type error: Type 'NonNullable<ReactElement<any, string | JSXElementConstructor<any>> | NavigationNode>[]' is not assignable to type 'NavigationNode[]'. " 

### Expected Behavior

Compilation success

### To Reproduce

Compilation on Ubuntu Server, on development on MacOS compilation has no problem

**Comment by paales** [comment]
Run `yarn add @types/react-is`, will be fixed in 7.0.1 (to be released shortly)

**Comment by milindsingh** [comment]
Hi  @paales 
I am still getting this error with 7.0.1 version.

```bash
- info Checking validity of types ...Failed to compile.

./node_modules/@graphcommerce/next-ui/Navigation/components/NavigationProvider.tsx:45:7
Type error: Type 'NonNullable<ReactElement<any, string | JSXElementConstructor<any>> | NavigationNode>[]' is not assignable to type 'NavigationNode[]'.
  Type 'NonNullable<ReactElement<any, string | JSXElementConstructor<any>> | NavigationNode>' is not assignable to type 'NavigationNode'.
    Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'NavigationNode'.
      Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'NavigationNodeButton'.
        Property 'id' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'NavigationNodeBase'.

  43 |       animating,
  44 |       closing,
> 45 |       items: items
     |       ^
  46 |         .map((item, index) =>
  47 |           isElement(item)
  48 |             ? ({
error Command failed with exit code 1.
```

**Comment by paales** [comment]
It has something to do with @types/react and @types/react-dom being installed twice with different versions. 

A resolutions field in package.json should help here. On mobile now can respond in more instructions if you aren’t able to figure it out.
