### ISSUE TITLE
The default install is not working with the issue "Cannot read properties of undefined (reading 'pages')"

### ISSUE THREAD

**Issue by HungDo-Niteco** [graphcommerce-org/graphcommerce#2074]
### Describe the Bug

Hi, I'm a newbie to the project.
I have a problem when setting up an install on docker. When I run **yarn dev** these bugs show up.
Let help me plz.
![image](https://github.com/graphcommerce-org/graphcommerce/assets/89763244/e5834fd9-f37a-453c-891c-c35b99cd9529)

### Expected Behavior

Working expected.

### To Reproduce

Run these command lines:
`$ yarn`
`$ yarn codegen`
`$ yarn dev`
This is my config:
**.env**
![image](https://github.com/graphcommerce-org/graphcommerce/assets/89763244/1a1b84d5-ba36-466d-9da2-a7aa9dadedb7)

**Comment by paales** [comment]
Can you to your package.json and install the node_modules again? 

```
  "resolutions": {
    "graphql-jit": "0.8.2"
  },
```

**Comment by HungDo-Niteco** [comment]
> Can you to your package.json and install the node_modules again?
> 
> ```
>   "resolutions": {
>     "graphql-jit": "0.8.2"
>   },
> ```

Good well, thank you so much.
I realized my code had expired for so long, that many packages were out of date. Just download the new code repo and re-install.
