### ISSUE TITLE
Cannot read properties of undefined (reading '__schema') when setup a magento endpoint localhost

### ISSUE THREAD

**Issue by HungDo-Niteco** [graphcommerce-org/graphcommerce#2080]
### Describe the Bug

Hi all,
I have a magento endpoint in my localhost, so when I put this point into .env file then run command line `yarn codegen` and it shows theses errors, can anyone help me resolve.
Thanks!

![image](https://github.com/graphcommerce-org/graphcommerce/assets/89763244/f0524415-769a-4e8d-bdd0-d1f5639c7978)

### Expected Behavior

Working perfect

### To Reproduce
Environment endpoint: `Magento-2.4.6-p1`
Put local endpoint to .env file: `GC_MAGENTO_ENDPOINT=https://magento2.test/graphql`
Run command line: `yarn codegen`

**Comment by HungDo-Niteco** [comment]
After thorough investigation, I have identified the root cause of the issue. The problem stems from Magento endpoint's CORS. However, I have successfully resolved CORS locally.

**Comment by wmycco1** [comment]
> After thorough investigation, I have identified the root cause of the issue. The problem stems from Magento endpoint's CORS. However, I have successfully resolved CORS locally.

This does not solve the problem not at the nginx level, not at the magento 2 level
