### ISSUE TITLE
Split sitemaps/robots.txt for separate domains when using i18n domain routing

### ISSUE THREAD

**Issue by hnsr** [graphcommerce-org/graphcommerce#2131]
### Describe the feature you'd like to request

Current robots/sitemap implementation has some issues when next.js i18n [domain routing](https://nextjs.org/docs/pages/building-your-application/routing/internationalization#getting-started) is used:

- When a locale has its own domain, URLs get generated with the globally configured `canonicalBaseUrl`  and the locale code prefixed in the URL path, instead of just using the locale domain (i.e. you get `shop.example.com/nl-nl/foo` instead of `shop.example.nl/foo`. This is probably easy to fix by taking into account the `i18n.domains` config.

- The `robots.txt` and `sitemap.xml` served from the different domains are identical, containing references to URLs for other locales even if they are served from a different domain. It may be desirable to have separate sitemaps for each domain, and specify different `robots.txt` policies for each domain. Seems harder to fix, there is https://github.com/iamvishnusankar/next-sitemap/issues/58, but this was closed as completed, without an actual solution

Some examples of setups to support:

**Global setup, without domain routing**
There are 3 locales, all available through the globally defined `canonicalBaseUrl`, of which `en-en` is marked as the default locale. This setup currently works, similar to GraphCommerce demo

```
shop.example.com        (en-en)
shop.example.com/nl-nl
shop.example.com/nl-be
```

**Partial-domain routing setup**
Here the `nl-nl` locale gets its own domain, the rest is served over the globally defined `canonicalBaseUrl` (no `i18n.domains` entry exists for `shop.example.com`)

```
shop.example.com       (en-en)
shop.example.com/nl-be
shop.example.nl        (nl-nl)
```

**Full-domain routing setup**
All locales get their own domain

```
shop.example.com (en-en)
shop.example.be  (nl-be)
shop.example.nl  (nl-nl)
```

**Multiple domains, multiple locales setup**
Multiple domains serve multiple locales. (This is something Next.js supports, but I am not fully sure if GraphCommerce supports this currently due to how `Config.storefronts` is transformed into Next.js config.)

```
shop.example.com        (en-en)
shop.example.com/nl-nl  (nl-nl)
shop.example.be         (nl-be)
shop.example.be/fr-be   (fr-be)
shop.example.be/en-be   (en-be)
```

### Describe the solution you'd like

- Ability to have sitemaps split automatically based on `i18n.domains` config
- Ability to specify different `robots.txt` policies for different domains
- Nice to have: ability to leverage some 'common' `robots.txt` configuration so domain-specific configurations don't have to repeat a lot of stuff.

### Describe alternatives you've considered

- Setting up a separate `next-sitemap` config for each domain. Feels a bit too messy and isn't a perfect solution if you still have some locales without its own domain, also requires some rewrite hackery.

**Comment by paales** [comment]
I believe this is mostly done on canary. https://github.com/graphcommerce-org/graphcommerce/pull/2223
