### ISSUE TITLE
GraphQL Document Validation failed with 3 errors

### ISSUE THREAD

**Issue by HungDo-Niteco** [graphcommerce-org/graphcommerce#2171]
### Describe the Bug

There were failures in ran `yarn codegen` when I extracted the code from the `canary` branch and performed the step-by-step installation that followed. These are the bugs:

![Screenshot_5](https://github.com/graphcommerce-org/graphcommerce/assets/89763244/bb05da91-0039-408c-bdad-13221a239c3b)

I then added additional attributes to graphql to correct these problems.

![image](https://github.com/graphcommerce-org/graphcommerce/assets/89763244/9e0ecde8-556c-415c-97e5-361f4c1196fd)

But the error still appears after I run the command `yarn codegen`

![image](https://github.com/graphcommerce-org/graphcommerce/assets/89763244/d3372d87-b14a-4091-8b4f-b35b52cff2ef)

### Expected Behavior

Codegen compiles successfully.

### To Reproduce

1. yarn
2. yarn codegen

**Comment by paales** [comment]
Hi @HungDo-Niteco!

`birth_day`, `birth_month`, and `local` are fields that are not available by default in Magento, so these fields are added by a third party plugin or some other way.

Adding mandatory input fields to an existing mutation is a breaking change is a GraphQL Schema, therefor I would never advise making fields like this mandatory.

You have two options from here;
1. Make sure the fields aren't mandatory so they aren't required to be filled in (this only fixes the codegen error, but you probably want to use them, so this isn't as useful).

2. Create the change you've created and make the necessary changes to the forms where they are used. Modifying the original file in this case can be a way to go. You can make them more permanent by creating a patch: https://www.graphcommerce.org/docs/framework/patch-package

In general I think we can improve here by not requiring modifications to the mutation and using a more general $input argument on the mutation. I'll create an issue on the backlog for this.

Does this help?

**Comment by HungDo-Niteco** [comment]
Hi @paales 
I don't know which fields come from, so which best practice do I need to fix these?
For the patch that fixed it, how can I fix it?

**Comment by paales** [comment]
@HungDo-Niteco Closing this issue as there is nothing we seem to be able to do from our side.
