### ISSUE TITLE
yarn codegen fails with error in powershell using node v16

### ISSUE THREAD

**Issue by lilithebowman** [graphcommerce-org/graphcommerce#2176]
### Describe the Bug

PS D:\Source\medication-ecomm> yarn codegen
yarn run v1.22.21
$ graphcommerce codegen-config && mesh build && graphql-codegen
No graphcommerce.config.js found in the project, using demo config
💡 🕸️  Mesh  Cleaning existing artifacts
💡 🕸️  Mesh  Reading the configuration
💡 🕸️  Mesh  Generating the unified schema
💡 🕸️  Mesh  Generating artifacts
💡 🕸️  Mesh  Generating index file in TypeScript
💡 🕸️  Mesh  Writing index.ts for CJS to the disk.
💡 🕸️  Mesh  Cleanup
💡 🕸️  Mesh  Done! => D:\Source\medication-ecomm\.mesh
√ Parse Configuration
‼ Generate outputs
  √ Generate to node_modules/@graphcommerce/graphql/generated/types.ts
  √ Generate to node_modules/@graphcommerce/graphql/generated/fragments.json
  > Generate to .
    √ Load GraphQL schemas
    √ Load GraphQL documents
    × fragment Asset @injectable { ... } can not be found or isn't injectable
      fragment AssetWithAlt on Asset @inject(into: ["Asset"]) { ... }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Expected Behavior

I can actually use this project

### To Reproduce

I cannot even begin to use it

**Comment by milindsingh** [comment]
I think Windows OS is not supported officially. Try with WSL
