### ISSUE TITLE
Type error: 'result.data.placeOrder.order' is possibly 'null' or 'undefined'.

### ISSUE THREAD

**Issue by softcommerceltd** [graphcommerce-org/graphcommerce#2269]
### Describe the Bug

The error is thrown during the execution of `yarn build` command.

It appears that the `order` interface was deprecated in Magento 2.4.7 in favour of `orderV2`.

**Tested with the following environment setup:**
OS: MacOS 14
Node: v18.19.0
Yarn: 4.1.1
GC release: 8.1.0-canary.12
Magento: 2.4.7

-----------
CLI output:

➜  graphcms-8.1.0-testing yarn build
🕸️  Mesh 💡 Cleaning existing artifacts
🕸️  Mesh 💡 Reading the configuration
🕸️  Mesh 💡 Generating the unified schema
🕸️  Mesh 💡 Generating artifacts
🕸️  Mesh 💡 Generating index file in TypeScript
🕸️  Mesh 💡 Writing index.ts for ESM to the disk.
🕸️  Mesh 💡 Cleanup
🕸️  Mesh 💡 Done! => .../graphcms-8.1.0-testing/.mesh
✔ Parse Configuration
✔ Generate outputs
   ▲ Next.js 14.1.0
   - Experiments (use at your own risk):
     · swcPlugins
     · scrollRestoration
     · bundlePagesExternals

   Skipping linting
   Checking validity of types  .Failed to compile.

./node_modules/@graphcommerce/magento-cart-payment-method/PaymentMethodPlaceOrderNoop/PaymentMethodPlaceOrderNoop.tsx:14:23
Type error: 'result.data.placeOrder.order' is possibly 'null' or 'undefined'.

  12 |     onComplete: async (result) => {
  13 |       if (!result.data?.placeOrder) return
> 14 |       await onSuccess(result.data.placeOrder.order.order_number)
     |                       ^
  15 |     },
  16 |   })
  17 |

-----------
Proposed changes:

replace the following code on line 13 in node_modules/@graphcommerce/magento-cart-payment-method/PaymentMethodPlaceOrderNoop/PaymentMethodPlaceOrderNoop.tsx

`if (!result.data?.placeOrder) return`

with

`if (!result.data?.placeOrder?.order) return`

### Expected Behavior

Running `yarn build` should return no errors.

### To Reproduce

- Install the latest Magento 2.4.7 release;
- Install the current canary branch [8.1.0-canary.12]
- Make appropriate configuration to connect to the new magento 2.4.7 instane
- Execute `yarn build` to reproduce the error.

**Comment by paales** [comment]
@softcommerceltd Whoops, after the discussion I had already applied the changes. Merged here: https://github.com/graphcommerce-org/graphcommerce/commit/831d7cd64a40b7b58748fd9637199b88938e75b7

Also available on the 8.x branch as GraphCommerce 8.0.6. Thanks a lot for bringing this to our attention 🙏

**Comment by softcommerceltd** [comment]
> @softcommerceltd Whoops, after the discussion I had already applied the changes. Merged here: [831d7cd](https://github.com/graphcommerce-org/graphcommerce/commit/831d7cd64a40b7b58748fd9637199b88938e75b7)
> 
> Also available on the 8.x branch as GraphCommerce 8.0.6. Thanks a lot for bringing this to our attention 🙏

Great it's sorted!
