### ISSUE TITLE
Can't set the dangerouslySetInnerHTML prop for the built-in Button component

### ISSUE THREAD

**Issue by UrosJeknic** [graphcommerce-org/graphcommerce#2375]
### Describe the Bug

I'm using useHits to get the hits from the built in SearchBox component and each of those hits has a _highlightResult property where I can find and return html to mark the keywords I put into the SearchBox component. 
The problem is THE PAGE CRASHES if I set the _html property to that html.
I tried just manually setting the inner html for the Button component just in case i might not be returning html from _highlightResult but it still crashes. Setting the inner html for any other component seems to work just not for the Button component. 

### Expected Behavior

I want the page to not crash and set the inner html

### To Reproduce

import { Button } from '@graphcommerce/next-ui'

<Button dangerouslySetInnerHTML={{ _html: anyHTML }} />

### Edit

I think it might have something to do with their being a child already inside the Button component

**Comment by paales** [comment]
Might this work?

```
<Button><span dangerouslySetInnerHTML={{ _html: anyHTML }}/></Button>
```

**Comment by paales** [comment]
:)
